### ISSUE TITLE
Build python-binding failed

### ISSUE THREAD

**Issue by wuxianshen** [eclipse-cyclonedds/cyclonedds-python#138]
I try to build the python-binding from source, but met the error:

ModuleNotFoundError: No module named 'cyclone_search'

Environment:
+ Windows 10
+ Anaconda

Installation step:
1) Install cyclonedds 0.10.1 from source: 
cmake -G "Visual Studio 16 2019" -A Win64 -DCMAKE_INSTALL_PREFIX=<install-location> ..
cmake --build . --target install
And the CMake examples helloworld works fine.
2) Install python-binding with anaconda:
In a system cmd:
D:\Software\Anaconda3\envs\pydds\python -m pip install cyclonedds --no-binary cyclonedds
The CYCLONEDDS_HOME variable is added to the system variable.

Error info:

`
D:\Tool\Software\CycloneDDS\0_10_1\cyclonedds-0.10.1>D:\Software\Anaconda3\envs\pydds\python -m pip install cyclonedds --no-binary cyclonedds
Collecting cyclonedds
  Using cached cyclonedds-0.9.1.tar.gz (94 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "D:\Software\Anaconda3\envs\pydds\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "D:\Software\Anaconda3\envs\pydds\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\Software\Anaconda3\envs\pydds\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\tao\AppData\Local\Temp\pip-build-env-6vb_rqud\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\tao\AppData\Local\Temp\pip-build-env-6vb_rqud\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\tao\AppData\Local\Temp\pip-build-env-6vb_rqud\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 23, in <module>
      ModuleNotFoundError: No module named 'cyclone_search'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
`

**Comment by thijsmie** [comment]
Hi @wuxianshen,

This error was because of a packaging error, the cyclone_search build-time module was not listed in the manifest thus not included in the source archive. You can solve this by building using the source from git (run a git clone, navigate to the folder and do a `pip install .`) or wait till the 0.10.2 patch is released (should hopefully be today).
