### ISSUE TITLE
Subscribing to a topic containing a union with an enum discriminator 

### ISSUE THREAD

**Issue by adam-lee** [eclipse-cyclonedds/cyclonedds-python#215]
With the following IDL:

```
➜ vcomm (production) ✗ cyclonedds typeof HelloWorldData_Msg
   0:00:01 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Entities discovered: 1

As defined in participant(s) 0110981a-ffe6-a83c-058c-67a7000001c1
module HelloWorldData {
    enum signal_value_type {
        integer_value,
        double_value,
        string_value
    };
    @final
    union value_s switch (HelloWorldData::signal_value_type) {
        case HelloWorldData::integer_value:
            unsigned long long int_value;
        case HelloWorldData::double_value:
            double double_value;
        case HelloWorldData::string_value:
            bounded_str<512>  str_value;
    };
    @final
    struct Msg {
        @key long userID;
        string message;
        HelloWorldData::value_s value;
    };
};
```

I can't subscribe to this topic using `cyclonedds subscribe` command:

```
> cyclonedds subscribe HelloWorldData_Msg

   0:00:01 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Entities discovered: 1

 Subscribing, CTRL-C to quit

Exception in thread Thread-3 (subscribe):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/cyclonedds/tools/cli/data/__init__.py", line 17, in subscribe
    tp = topic.Topic(dp, topic_name, datatype, qos=topicqos)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cyclonedds/topic.py", line 55, in __init__
    data_type.__idl__.fill_type_data()
  File "/opt/homebrew/lib/python3.11/site-packages/cyclonedds/idl/_main.py", line 318, in fill_type_data
    self._xt_data = XTBuilder.process_type(self.datatype)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cyclonedds/idl/_xt_builder.py", line 266, in process_type
    scc_typeids = cls._handle_component(_names, _types, _graph, _type_component_ids, _component_sizes, _component_graph, 0)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cyclonedds/idl/_xt_builder.py", line 490, in _handle_component
    scc_typeids = sum([
                      ^
  File "/opt/homebrew/lib/python3.11/site-packages/cyclonedds/idl/_xt_builder.py", line 491, in <listcomp>
    cls._handle_component(
  File "/opt/homebrew/lib/python3.11/site-packages/cyclonedds/idl/_xt_builder.py", line 504, in _handle_component
    hash: TypeHash = cls._resolve_typehash(_names[i], _types[i])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cyclonedds/idl/_xt_builder.py", line 470, in _resolve_typehash
    minimal_object = cls._xt_minimal_type_object(_type)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cyclonedds/idl/_xt_builder.py", line 793, in _xt_minimal_type_object
    return xt.MinimalTypeObject(union_type=cls._xt_minimal_union_type(entity))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cyclonedds/idl/_xt_builder.py", line 1065, in _xt_minimal_union_type
    member_seq=cls._xt_minimal_union_member_seq(entity)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cyclonedds/idl/_xt_builder.py", line 1116, in _xt_minimal_union_member_seq
    return [
           ^
  File "/opt/homebrew/lib/python3.11/site-packages/cyclonedds/idl/_xt_builder.py", line 1117, in <listcomp>
    cls._xt_minimal_union_member(entity, name, _type)
  File "/opt/homebrew/lib/python3.11/site-packages/cyclonedds/idl/_xt_builder.py", line 1139, in _xt_minimal_union_member
    common=cls._xt_common_union_member(entity, name, _type, True),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cyclonedds/idl/_xt_builder.py", line 1160, in _xt_common_union_member
    label_seq=cls._xt_union_case_label_seq(entity, name, _type)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cyclonedds/idl/_xt_builder.py", line 1166, in _xt_union_case_label_seq
    return [l.value for l in _type.labels] if isinstance(_type, pt.case) else []
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cyclonedds/idl/_xt_builder.py", line 1166, in <listcomp>
    return [l.value for l in _type.labels] if isinstance(_type, pt.case) else []
            ^^^^^^^
AttributeError: 'int' object has no attribute 'value'
^C
```

Is this expected...? Ty!

**Comment by adam-lee** [comment]
Sharing what @eboasson shared on Discord in case someone else is having this problem:

> It is supposed to work, it doesn't (on `master`) with the type in the GitHub issue you created (https://github.com/eclipse-cyclonedds/cyclonedds-python/issues/215). So I'm afraid you ran into a bug ...

> By the way, you might be able to use the `dynsub` example as a workaround. That one more complete than it should be considering that it was meant to be an *example* of reading a dynamically discovered topic, rather than a full-fledged DDS-to-JSON tool ... Oh well ...

> You’re welcome to try older versions, but in my experience it is very rare for master to do worse than a release (something I’m quite proud of actually!)

This confirms that I'm not violating any rules in my IDL. So I'm content. Ty!
