### ISSUE TITLE
Failed to load CycloneDDS library from C:\bin\ddsc.dll

### ISSUE THREAD

**Issue by avelin0** [eclipse-cyclonedds/cyclonedds-python#276]
Hello, I'm getting this error when trying to import cyclonedds-nightly. I have tried different versions of cyclonedds-nightly, but I'm getting the same error message. This here using cyclonedds-nightly 2024.10.12 and python 3.11.9 appear "Failed to load CycloneDDS library from C:\bin\ddsc.dll" but this lib is there.

```
Traceback (most recent call last):
  File "C:\Users\avelino.bruno\PycharmProjects\proj-cyclonedds\.venv\Lib\site-packages\cyclonedds\internal.py", line 34, in _load
    library = ct.CDLL(path)
              ^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\bin\ddsc.dll' (or one of its dependencies). Try using the full path with constructor syntax.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\avelino.bruno\PycharmProjects\proj-cyclonedds\main.py", line 1, in <module>
    from cyclonedds import *
  File "C:\Users\avelino.bruno\PycharmProjects\proj-cyclonedds\.venv\Lib\site-packages\cyclonedds\__init__.py", line 13, in <module>
    from . import internal, util, qos, core, domain, topic, pub, sub, builtin, dynamic, idl
  File "C:\Users\avelino.bruno\PycharmProjects\proj-cyclonedds\.venv\Lib\site-packages\cyclonedds\internal.py", line 233, in <module>
    class DDS:
  File "C:\Users\avelino.bruno\PycharmProjects\proj-cyclonedds\.venv\Lib\site-packages\cyclonedds\internal.py", line 237, in DDS
    _dll_handle = load_cyclonedds()
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\avelino.bruno\PycharmProjects\proj-cyclonedds\.venv\Lib\site-packages\cyclonedds\internal.py", line 132, in load_cyclonedds
    lib = loader()
          ^^^^^^^^
  File "C:\Users\avelino.bruno\PycharmProjects\proj-cyclonedds\.venv\Lib\site-packages\cyclonedds\internal.py", line 58, in _loader_cyclonedds_home
    return _load(os.path.join(os.environ["CYCLONEDDS_HOME"], name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\avelino.bruno\PycharmProjects\proj-cyclonedds\.venv\Lib\site-packages\cyclonedds\internal.py", line 36, in _load
    raise CycloneDDSLoaderException(f"Failed to load CycloneDDS library from {path}")
cyclonedds.internal.CycloneDDSLoaderException: Failed to load CycloneDDS library from C:\bin\ddsc.dll
```

**Comment by noxpardalis** [comment]
I also ran into something similar. I think I've narrowed down to some oddness in https://docs.python.org/3/library/ctypes.html#ctypes.CDLL on Windows. If https://github.com/eclipse-cyclonedds/cyclonedds-python/blob/da68496a8eadc026b0b85786c616e12002d58ced/cyclonedds/internal.py#L35 is changed to the following:

```py
```
